language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.8"
     - PRETTYNAME="TravisPracticeArduinoLib"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
#   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
#   - sleep 3
#   - export DISPLAY=:1.0
#   - wget http://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz
#   - tar xf arduino-1.8.8-linux64.tar.xz
#   - sudo mv arduino-1.8.8 /usr/local/share/arduino
#   - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
# install:
#   - ln -s $PWD /usr/local/share/arduino/libraries/TravisPracticeArduinoLib
#   - arduino --install-library "TravisPracticeArduinoLib"
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

script:
#  - build_main_platforms
# Hello
  - arduino --verify --board arduino:avr:leonardo $PWD/examples/Hello/Hello.ino
  - arduino --verify --board arduino:samd:arduino_zero_native $PWD/examples/Hello/Hello.ino
  - arduino --verify --board adafruit:samd:adafruit_metro_m4 $PWD/examples/Hello/Hello.ino
  - arduino --verify --board esp32:esp32:featheresp32:FlashFreq=80 $PWD/examples/Hello/Hello.ino
  - arduino --verify --board esp8266:esp8266:huzzah:eesz=4M3M,xtal=80 $PWD/examples/Hello/Hello.ino
  - arduino --verify --board arduino:avr:mega:cpu=atmega2560 $PWD/examples/Hello/Hello.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Hello/Hello.ino
  - arduino --verify --board arduino:sam:arduino_due_x $PWD/examples/Hello/Hello.ino
# PassUno
  - arduino --verify --board arduino:avr:uno $PWD/examples/PassUno/PassUno.ino
# PassArduinoZero
  - arduino --verify --board arduino:samd:arduino_zero_native $PWD/examples/PassUno/PassUno.ino

notifications:
  email:
    on_success: change
    on_failure: change
